### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by crshrprt** [pauljonescodes/pro-punk-drums#1]
Thank you for this interesting plugin.

Is there any chance to have a Linux version? Since it's made with JUCE it should be quite easy to build it.

I tried to build it for Linux from the source code by adding a Linux exporter in Projucer, however it complains about the missing wav files.

**Comment by pauljonescodes** [comment]
Certainly! I use Linux for work, to be honest I figured no one ran plugins on it, but I'm sure I can get it built for Linux. I'll comment back here when I have it.

Thanks for checking it out :)

**Comment by crshrprt** [comment]
That's great! Thank you very much.

If I may ask, are the samples contained in the plugin going to available in this repo or another at some point? Are they going to be released as public domain or other CC license?

**Comment by pauljonescodes** [comment]
They're currently not, which I did just out of cautiousness, with the passing of time and your interest, I'm happy to make them available too.

**Comment by crshrprt** [comment]
Thank you again, this will be a wonderful addition to the libre resources for musicians.

**Comment by dingodoppelt** [comment]
> They're currently not, which I did just out of cautiousness, with the passing of time and your interest, I'm happy to make them available too.

Interest + 1  
Thanks for your efforts. Really looking forward to playing your kit :)

**Comment by pauljonescodes** [comment]
You shall find a Linux VST3 and standalone executable under the releases! Further, I've added the samples to this repo, along with a default preset. Let me know if it works! To be honest, building it was quite easy, but testing was a little tricky, it _seems_ fine but I can't be certain.
